project/app1/urls.py
import imp
from django.urls import path
from .views import StartView

app_name = 'app1'
urlpatterns = [
    path('', StartView.as_view(), name='start'),
]

project/app3/urls.py
from django.urls import path
from .views import Nutrition, NutritionsCreateView, NutritionsUpdateView, NutritionsDeleteView, TargetCreateView, TargetUpdateView
from . import views

app_name = 'app3'
urlpatterns = [
    path('nutrition/', Nutrition.as_view(), name='nutrition'),
    path('create/nutrition/', NutritionsCreateView.as_view(), name='create_nutrition'),
    path('create_target/', TargetCreateView.as_view(), name='create_target'),
    path('update_target/<int:pk>', TargetUpdateView.as_view(), name='update_target'),
    path('update/<int:pk>', NutritionsUpdateView.as_view(), name='update_nutrition'),
    path('delete/<int:pk>', NutritionsDeleteView.as_view(), name='delete_nutrition'),
    path('reset/nutrition/', views.reset, name='reset_nutrition'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('app2.urls')),
    path('', include('app3.urls')),
    
    # allauth アプリが持つビューを url と紐付け
    path('account/', include('allauth.urls')),
]

project/app3/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Nutritions(models.Model):
    food = models.CharField(max_length=100, blank=False, null=False)
    calorie = models.IntegerField(blank=False, null=False)
    protein = models.FloatField(blank=False, null=False)
    carbohydrate = models.FloatField(blank=False, null=False)
    lipid = models.FloatField(blank=False, null=False)
    created_at = models.DateTimeField(default=timezone.now)

class Target(models.Model):
    target_calorie = models.IntegerField(blank=False, null=False)
    target_protein = models.FloatField(blank=False, null=False)
    target_carbohydrate = models.FloatField(blank=False, null=False)
    target_lipid = models.FloatField(blank=False, null=False)

project/app3/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import Nutritions, Target

class NutritionsForm(forms.ModelForm):
    
    class Meta:
        # どのモデルを利用するのか
        model = Nutritions
        # 表示させるフィールド
        fields = ['food', 'calorie', 'protein', 'carbohydrate', 'lipid']
        widgets = {
            'food': forms.TextInput(),
            'calorie': forms.NumberInput(),
            'protein': forms.NumberInput(),
            'carbohydrate': forms.NumberInput(),
            'lipid': forms.NumberInput(),
        }
        labels = {
            'food': '食品',
            'calorie': 'カロリー',
            'protein': 'タンパク質',
            'carbohydrate': '炭水化物',
            'lipid': '脂質',
        }

class TargetForm(forms.ModelForm):
    
    class Meta:
        model = Target
        fields = ['target_calorie', 'target_protein', 'target_carbohydrate', 'target_lipid']
        widgets = {
            'target_calorie': forms.NumberInput(),
            'target_protein': forms.NumberInput(),
            'target_carbohydrate': forms.NumberInput(),
            'target_lipid': forms.NumberInput(),
        }
        labels = {
            'target_calorie': '目標カロリー',
            'target_protein': '目標タンパク質',
            'target_carbohydrate': '目標炭水化物',
            'target_lipid': '目標脂質',
        }

project/app3/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView
from .models import Nutritions, Target
from .forms import NutritionsForm, TargetForm
from django.urls import reverse_lazy

# Create your views here.
class Nutrition(TemplateView):
    template_name: str = 'app3/nutritions.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if len(Target.objects.all()) > 0 and len(Nutritions.objects.all()) > 0:
            # 入力値の取得
            context["nutritions"] = Nutritions.objects.all()
            
            # 各値の合計値
            sum_calorie = []
            sum_protein = []
            sum_carbohydrate = []
            sum_lipid = []
            for i in range(len((Nutritions.objects.values_list('calorie')))):
                sum_calorie.append(Nutritions.objects.values_list('calorie')[i][0])
                sum_protein.append(Nutritions.objects.values_list('protein')[i][0])
                sum_carbohydrate.append(Nutritions.objects.values_list('carbohydrate')[i][0])
                sum_lipid.append(Nutritions.objects.values_list('lipid')[i][0])
            context["sum_calorie"] = sum(sum_calorie)
            context["sum_protein"] = sum(sum_protein)
            context["sum_carbohydrate"] = sum(sum_carbohydrate)
            context["sum_lipid"] = sum(sum_lipid)
            
            context["target_id"] = Target.objects.values_list('id')[len(Target.objects.values_list('id'))-1][0]
            
            # 目標の取得(データの一番後ろのデータを取得) ※更新しているわけではない
            context["target_calorie"] = Target.objects.values_list('target_calorie')[len(Target.objects.values_list('target_calorie'))-1][0]
            context["target_protein"] = Target.objects.values_list('target_protein')[len(Target.objects.values_list('target_protein'))-1][0]
            context["target_carbohydrate"] = Target.objects.values_list('target_carbohydrate')[len(Target.objects.values_list('target_carbohydrate'))-1][0]
            context["target_lipid"] = Target.objects.values_list('target_lipid')[len(Target.objects.values_list('target_lipid'))-1][0]
        
            # 目標値と入力値の差
            context["sub_calorie"] =  context["sum_calorie"] - context["target_calorie"]
            context["sub_protein"] =  context["sum_protein"] - context["target_protein"]
            context["sub_carbohydrate"] = context["sum_carbohydrate"] - context["target_carbohydrate"]
            context["sub_lipid"] = context["sum_lipid"] - context["target_lipid"]
            
            return context
        
        # Nutritionsにデータが入っていた場合
        elif len(Nutritions.objects.all()) > 0:
            # 入力値の取得
            context["nutritions"] = Nutritions.objects.all()
            
            # 各値の合計値
            sum_calorie = []
            sum_protein = []
            sum_carbohydrate = []
            sum_lipid = []
            for i in range(len((Nutritions.objects.values_list('calorie')))):
                sum_calorie.append(Nutritions.objects.values_list('calorie')[i][0])
                sum_protein.append(Nutritions.objects.values_list('protein')[i][0])
                sum_carbohydrate.append(Nutritions.objects.values_list('carbohydrate')[i][0])
                sum_lipid.append(Nutritions.objects.values_list('lipid')[i][0])
            context["sum_calorie"] = sum(sum_calorie)
            context["sum_protein"] = sum(sum_protein)
            context["sum_carbohydrate"] = sum(sum_carbohydrate)
            context["sum_lipid"] = sum(sum_lipid)
            
            return context
        
        # Targetにデータが入っていた場合
        elif len(Target.objects.all()) > 0:
            context["target_id"] = Target.objects.values_list('id')[len(Target.objects.values_list('id'))-1][0]
            
            # 目標の取得(データの一番後ろのデータを取得) ※更新しているわけではない
            context["target_calorie"] = Target.objects.values_list('target_calorie')[len(Target.objects.values_list('target_calorie'))-1][0]
            context["target_protein"] = Target.objects.values_list('target_protein')[len(Target.objects.values_list('target_protein'))-1][0]
            context["target_carbohydrate"] = Target.objects.values_list('target_carbohydrate')[len(Target.objects.values_list('target_carbohydrate'))-1][0]
            context["target_lipid"] = Target.objects.values_list('target_lipid')[len(Target.objects.values_list('target_lipid'))-1][0]
            
            return context
        
        # Nutritions または Target にデータが入っていなかった場合
        else:
            context["sum_calorie"] = 0
            context["sum_protein"] = 0
            context["sum_carbohydrate"] = 0
            context["sum_lipid"] = 0
            
            # 目標の取得(データの一番後ろのデータを取得) ※更新しているわけではない
            context["target_calorie"] = 0
            context["target_protein"] = 0
            context["target_carbohydrate"] = 0
            context["target_lipid"] = 0
            
            # 目標値と入力値の差
            context["sub_calorie"] =  0
            context["sub_protein"] =  0
            context["sub_carbohydrate"] = 0
            context["sub_lipid"] = 0
            
            return context


class NutritionsCreateView(CreateView):
    model = Nutritions
    template_name = "app3/create.html"
    form_class = NutritionsForm
    success_url = reverse_lazy('app3:nutrition')

class NutritionsUpdateView(UpdateView):
    model = Nutritions
    template_name = "app3/update.html"
    fields = ['food', 'calorie', 'protein', 'carbohydrate', 'lipid']
    success_url = reverse_lazy('app3:nutrition')

class NutritionsDeleteView(DeleteView):
    model = Nutritions
    template_name = "app3/delete.html"
    success_url = reverse_lazy('app3:nutrition')

# 目標値 設定
class TargetCreateView(CreateView):
    model = Target
    form_class = TargetForm
    template_name = "app3/create_target.html"
    success_url = reverse_lazy('app3:nutrition')
    
class TargetUpdateView(UpdateView):
    model = Target
    template_name = "app3/update_target.html"
    fields = ['target_calorie', 'target_protein', 'target_carbohydrate', 'target_lipid']
    success_url = reverse_lazy('app3:nutrition')

# リセット
def reset(request):
    Target.objects.all().delete()
    Nutritions.objects.all().delete()
    context = {}
    context["sum_calorie"] = 0
    context["sum_protein"] = 0
    context["sum_carbohydrate"] = 0
    context["sum_lipid"] = 0
    
    # 目標の取得(データの一番後ろのデータを取得) ※更新しているわけではない
    context["target_calorie"] = 0
    context["target_protein"] = 0
    context["target_carbohydrate"] = 0
    context["target_lipid"] = 0
    
    # 目標値と入力値の差
    context["sub_calorie"] =  0
    context["sub_protein"] =  0
    context["sub_carbohydrate"] = 0
    context["sub_lipid"] = 0
    
    return render(request, 'app3/nutritions.html', context)

project/templates/app3/create.html
{% extends '../layouts/base3.html' %}

{% block title %}
Today's Nutrition
{% endblock title %}

{% block contents %}
<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <td class="label">今日の栄養摂取</td>
                    <td></td>
                </tr>
            </thead>
            {% with form as f %}
            <tbody>
                <tr>
                    <td class="label">{{ f.food.label }}</td>
                    <td>{{ f.food }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.calorie.label }}</td>
                    <td>{{ f.calorie }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.protein.label }}</td>
                    <td>{{ f.protein }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.carbohydrate.label }}</td>
                    <td>{{ f.carbohydrate }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.lipid.label }}</td>
                    <td>{{ f.lipid }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="保存"></td>
                </tr>
            </tbody>
            {% endwith %}
        </table>
    </form>
</div>
{% endblock contents %}

project/templates/app3/create_target.html
{% extends '../layouts/base3.html' %}

{% block title %}
Today's Target Nutrition
{% endblock title %}

{% block contents %}
<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <td class="label">今日の目標</td>
                    <td></td>
                </tr>
            </thead>
            {% with form as f %}
            <tbody>
                <tr>
                    <td class="label">{{ f.target_calorie.label }}</td>
                    <td>{{ f.target_calorie }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.target_protein.label }}</td>
                    <td>{{ f.target_protein }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.target_carbohydrate.label }}</td>
                    <td>{{ f.target_carbohydrate }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.target_lipid.label }}</td>
                    <td>{{ f.target_lipid }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="保存"></td>
                </tr>
            </tbody>
            {% endwith %}
        </table>
    </form>
</div>
{% endblock contents %}

project/templates/app3/delete.html
{% extends '../layouts/base3.html' %}

{% block title %}
Delete page
{% endblock title %}

{% block contents %}
<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <tr class="column_names">
                <th>food</th>
                <th>calorie</th>
                <th>protein</th>
                <th>carbohydrate</th>
                <th>lipid</th>
                <th>created_at</th>
            </tr>
            <tr>
                <th>{{ nutritions.food }}</th>
                <th>{{ nutritions.calorie }}</th>
                <th>{{ nutritions.protein }}</th>
                <th>{{ nutritions.carbohydrate }}</th>
                <th>{{ nutritions.lipid }}</th>
                <th>{{ nutritions.created_at }}</th>
            </tr>
            <tr>
                <th><input type="submit" value="delete!"></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th><button><a href="{% url 'app3:nutrition' %}">戻る</a></button></th>
            </tr>
        </table>
        
    </form>
</div>
{% endblock contents %}

project/templates/app3/nutritions.html
{% extends '../layouts/base3.html' %}

{% block title %}
Today's Nutrition
{% endblock title %}

{% block contents %}
<div class="table">
    <table>
        <tr class="column_names">
            <th>食品</th>
            <th>カロリー</th>
            <th>タンパク質</th>
            <th>炭水化物</th>
            <th>脂質</th>
            <th>作成日</th>
            <th>update</th>
            <th>delete</th>
        </tr>

        <tr class="target">
            <td>目標値</td>
            <td>{{ target_calorie }}</td>
            <td>{{ target_protein }}</td>
            <td>{{ target_carbohydrate }}</td>
            <td>{{ target_lipid }}</td>
            <td></td>
            {% if target_id %}
            <td><button><a href="{% url 'app3:update_target' target_id %}">編集</a></button></td>
            {% else %}
            <td></td>
            {% endif %}
            <td></td>
        </tr>
        
        <tr class="sum">
            <td>合計値</td>
            <td>{{ sum_calorie }}</td>
            <td>{{ sum_protein }}</td>
            <td>{{ sum_carbohydrate }}</td>
            <td>{{ sum_lipid }}</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        <tr class="result">
            <td>結果</td>
            <td>{{ sub_calorie }}</td>
            <td>{{ sub_protein }}</td>
            <td>{{ sub_carbohydrate }}</td>
            <td>{{ sub_lipid }}</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        

        {% for nutrition in nutritions %}
        <tr>
            <td>{{ nutrition.food }}</td>
            <td>{{ nutrition.calorie }}</td>
            <td>{{ nutrition.protein }}</td>
            <td>{{ nutrition.carbohydrate }}</td>
            <td>{{ nutrition.lipid }}</td>
            <td>{{ nutrition.created_at }}</td>
            <td><button><a href="{% url 'app3:update_nutrition' nutrition.id %}">編集</a></button></td>
            <td><button><a href="{% url 'app3:delete_nutrition' nutrition.id %}">削除</a></button></td>
        </tr>
        {% endfor %}
    </table>
    <button id="reset"><a href="{% url 'app3:reset_nutrition' %}">リセット</a></button>
</div>
{% endblock contents %}

project/templates/app3/update.html
{% extends '../layouts/base3.html' %}

{% block title %}
Nutrition Update
{% endblock title %}

{% block contents %}

<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <td><h1>Update of Nutrition</h1></td>
                </tr>
            </thead>
            {% with form as f %}
            <tbody>
                <tr>
                    <td>{{ f.food.label }}</td>
                    <td>{{ f.food }}</td>
                </tr>
                <tr>
                    <td>{{ f.calorie.label }}</td>
                    <td>{{ f.calorie }}</td>
                </tr>
                <tr>
                    <td>{{ f.protein.label }}</td>
                    <td>{{ f.protein }}</td>
                </tr>
                <tr>
                    <td>{{ f.carbohydrate.label }}</td>
                    <td>{{ f.carbohydrate }}</td>
                </tr>
                <tr>
                    <td>{{ f.lipid.label }}</td>
                    <td>{{ f.lipid }}</td>
                </tr>
                <tr>
                    <td><button><a href="{% url 'app3:nutrition' %}">戻る</a></button></td>
                    <td><input type="submit" value="保存"></td>
                </tr>
            </tbody>
            {% endwith %}
        </table>
    </form>
</div>
{% endblock contents %}

project/templates/app3/update_target.html
{% extends '../layouts/base3.html' %}

{% block title %}
Nutrition Update
{% endblock title %}

{% block contents %}

<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <td><h1>Update of Nutrition</h1></td>
                </tr>
            </thead>
            {% with form as f %}
            <tbody>
                <tr>
                    <td>{{ f.target_food.label }}</td>
                    <td>{{ f.target_food }}</td>
                </tr>
                <tr>
                    <td>{{ f.target_calorie.label }}</td>
                    <td>{{ f.target_calorie }}</td>
                </tr>
                <tr>
                    <td>{{ f.target_protein.label }}</td>
                    <td>{{ f.target_protein }}</td>
                </tr>
                <tr>
                    <td>{{ f.target_carbohydrate.label }}</td>
                    <td>{{ f.target_carbohydrate }}</td>
                </tr>
                <tr>
                    <td>{{ f.target_lipid.label }}</td>
                    <td>{{ f.target_lipid }}</td>
                </tr>
                <tr>
                    <td><button><a href="{% url 'app3:nutrition' %}">戻る</a></button></td>
                    <td><input type="submit" value="保存"></td>
                </tr>
            </tbody>
            {% endwith %}
        </table>
    </form>
</div>
{% endblock contents %}