project/app1/urls.py
import imp
from django.urls import path
from .views import StartView

app_name = 'app1'
urlpatterns = [
    path('', StartView.as_view(), name='start'),
]

project/app2/urls.py
from django.urls import path
from .views import ConditionCreateView, IndexView, ConditionUpdateView, ConditionDeleteView, ConditionGraphView
from . import views

app_name = 'app2'
urlpatterns = [
    path('create/condition/', ConditionCreateView.as_view(), name='create_condition'),
    path('update/<int:pk>/', ConditionUpdateView.as_view(), name='update_condition'),
    path('delete/<int:pk>/', ConditionDeleteView.as_view(), name='delete_condition'),
    path('reset/condition/', views.reset, name='reset_condition'),
    path('index/', IndexView.as_view(), name='index'),
    path('graph/', ConditionGraphView.as_view(), name='graph'),
    path('plot/', views.getPlot, name='plot'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('app2.urls')),
    path('', include('app3.urls')),
    
    # allauth アプリが持つビューを url と紐付け
    path('account/', include('allauth.urls')),
]

project/app2/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Condition(models.Model):
    height = models.FloatField(null=False)
    weight = models.FloatField(null=False)
    fat = models.FloatField()
    waist = models.FloatField()
    created_at = models.DateTimeField(default=timezone.now)
    
    def __float__(self):
        return self.weight
    

project/app2/forms.py
from django import forms
from .models import Condition

class ConditionForm(forms.ModelForm):
    
    class Meta:
        # どのモデルを利用するのか
        model = Condition
        # 表示させるフィールド
        fields = ['height', 'weight', 'fat', 'waist']
        widgets = {
            'height': forms.NumberInput(),
            'weight': forms.NumberInput(),
            'fat': forms.NumberInput(),
            'waist': forms.NumberInput(),
        }
        label = {
            'height': '身長',
            'weight': '体重',
            'fat': '体脂肪率',
            'waist': '腹囲',
        }

project/app2/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from .forms import ConditionForm
from .models import Condition
from django.urls import reverse_lazy
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import io
import datetime as dt


class ConditionCreateView(CreateView):
    # モデルを指定する
    model = Condition
    # フォームを指定する
    form_class = ConditionForm
    # テンプレートを指定する
    template_name = "app2/create.html"
    # フォーム送信完了後の遷移ページを指定する
    success_url = reverse_lazy("app2:index")

class ConditionUpdateView(UpdateView):
    model = Condition
    template_name = "app2/update.html"
    fields = ['height', 'weight', 'fat', 'waist']
    success_url = reverse_lazy('app2:index')

class ConditionDeleteView(DeleteView):
    model = Condition
    template_name = "app2/delete.html"
    success_url = reverse_lazy('app2:index')

class IndexView(ListView):
    template_name: str = 'app2/index.html'
    model = Condition
    context_object_name = 'conditions'
    paginate_by: int = 30

class ConditionGraphView(TemplateView):
    template_name = "app2/graph.html"
    
# リセット
def reset(request):
    Condition.objects.all().delete()
    return render(request, 'app2/index.html')

# グラフの描画
def getPlot(request):
    setPlt()
    svg = pltToSvg()
    plt.cla()
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response

# グラフ作成
def setPlt():
    # 折れ線グラフを出力
    created_at_list = []
    for created_at in Condition.objects.values_list('created_at'):
        t = created_at[0]+dt.timedelta(hours=9)
        created_at_list.append(t)
    x = np.array(created_at_list)
    # x = np.array(Condition.objects.values_list('created_at'))
    y = np.array(Condition.objects.values_list('weight'))
    
    plt.figure(figsize=(20,10))
    plt.plot(x, y)
    plt.xlabel("time")
    plt.ylabel("weight")
    plt.show()


# SVG化
def pltToSvg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s

project/templates/app2/create.html
{% extends '../layouts/base2.html' %}

{% block title %}
Today's Condition
{% endblock title %}

{% block contents %}
<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <td class="label">今日のコンディションは？</td>
                </tr>
            </thead>
            {% with form as f %}
            <tbody>
                <tr>
                    <td class="label">{{ f.height.label }}</td>
                    <td>{{ f.height }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.weight.label }}</td>
                    <td>{{ f.weight }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.fat.label }}</td>
                    <td>{{ f.fat }}</td>
                </tr>
                <tr>
                    <td class="label">{{ f.waist.label }}</td>
                    <td>{{ f.waist }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="保存"></td>
                </tr>
            </tbody>
            {% endwith %}
        </table>
    </form>
</div>
{% endblock contents %}

project/templates/app2/delete.html
{% extends '../layouts/base2.html' %}

{% block title %}
Delete Condition
{% endblock title %}

{% block contents %}
<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <tr class="column_names">
                <th>height</th>
                <th>weight</th>
                <th>fat</th>
                <th>waist</th>
                <th>created_at</th>
            </tr>
            <tr>
                <th>{{ condition.height }}</th>
                <th>{{ condition.weight }}</th>
                <th>{{ condition.fat }}</th>
                <th>{{ condition.waist }}</th>
                <th>{{ condition.created_at }}</th>
            </tr>
            <tr>
                <th><button><a href="{% url 'app2:index' %}">戻る</a></button></th>
                <th></th>
                <th></th>
                <th></th>
                <th><input type="submit" value="delete!"></th>
            </tr>
        </table>
    </form>
</div>
{% endblock contents %}

project/templates/app2/graph.html
{% extends '../layouts/base2.html' %}

{% block title %}
Graph of Conditions
{% endblock title %}

{% block contents %}
<div class="graph">
    <img src="{% url 'app2:plot' %}">
</div>
{% endblock contents %}

project/templates/app2/index.html
{% extends '../layouts/base2.html' %}

{% block title %}
Conditions
{% endblock title %}

{% block contents %}
<div class="tabel">
    <table>
        <tr class="column_names">
            <th>身長</th>
            <th>体重</th>
            <th>体脂肪率</th>
            <th>ウエスト</th>
            <th>作成日</th>
            <th>update</th>
            <th>delete</th>
        </tr>
        {% for condition in conditions %}
        <tr>
            <td>{{ condition.height }}</td>
            <td>{{ condition.weight }}</td>
            <td>{{ condition.fat }}</td>
            <td>{{ condition.waist }}</td>
            <td>{{ condition.created_at }}</td>
            <td><button><a href="{% url 'app2:update_condition' condition.id %}">編集</a></button></td>
            <td><button><a href="{% url 'app2:delete_condition' condition.id %}">削除</a></button></td>
        </tr>
        {% endfor %}
    </table>
    <button id="reset"><a href="{% url 'app2:reset_condition' %}">リセット</a></button>
</div>
{% endblock contents %}

project/templates/app2/update.html
{% extends '../layouts/base2.html' %}

{% block title %}
Today's Condition
{% endblock title %}

{% block contents %}
<div class="table">
    <form method="post">
    {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <td><h1>Update of Condition</h1></td>
                </tr>
            </thead>
            {% with form as f %}
            <tbody>
                <tr>
                    <td>{{ f.height.label }}</td>
                    <td>{{ f.height }}</td>
                </tr>
                <tr>
                    <td>{{ f.weight.label }}</td>
                    <td>{{ f.weight }}</td>
                </tr>
                <tr>
                    <td>{{ f.fat.label }}</td>
                    <td>{{ f.fat }}</td>
                </tr>
                <tr>
                    <td>{{ f.waist.label }}</td>
                    <td>{{ f.waist }}</td>
                </tr>
                <tr>
                    <td><button><a href="{% url 'app2:index' %}">戻る</a></button></td>
                    <td><input type="submit" value="保存"></td>
                </tr>
            </tbody>
            {% endwith %}
        </table>
    </form>
</div>
{% endblock contents %}