project/app1/urls.py
import imp
from django.urls import path
from .views import StartView

app_name = 'app1'
urlpatterns = [
    path('', StartView.as_view(), name='start'),
]

project/app2/urls.py
from django.urls import path
from .views import ConditionCreateView, IndexView, ConditionUpdateView, ConditionDeleteView, ConditionGraphView
from . import views

app_name = 'app2'
urlpatterns = [
    path('create/condition/', ConditionCreateView.as_view(), name='create_condition'),
    path('update/<int:pk>/', ConditionUpdateView.as_view(), name='update_condition'),
    path('delete/<int:pk>/', ConditionDeleteView.as_view(), name='delete_condition'),
    path('reset/condition/', views.reset, name='reset_condition'),
    path('index/', IndexView.as_view(), name='index'),
    path('graph/', ConditionGraphView.as_view(), name='graph'),
    path('plot/', views.getPlot, name='plot'),
]

project/app3/urls.py
from django.urls import path
from .views import Nutrition, NutritionsCreateView, NutritionsUpdateView, NutritionsDeleteView, TargetCreateView, TargetUpdateView
from . import views

app_name = 'app3'
urlpatterns = [
    path('nutrition/', Nutrition.as_view(), name='nutrition'),
    path('create/nutrition/', NutritionsCreateView.as_view(), name='create_nutrition'),
    path('create_target/', TargetCreateView.as_view(), name='create_target'),
    path('update_target/<int:pk>', TargetUpdateView.as_view(), name='update_target'),
    path('update/<int:pk>', NutritionsUpdateView.as_view(), name='update_nutrition'),
    path('delete/<int:pk>', NutritionsDeleteView.as_view(), name='delete_nutrition'),
    path('reset/nutrition/', views.reset, name='reset_nutrition'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('app2.urls')),
    path('', include('app3.urls')),
    
    # allauth アプリが持つビューを url と紐付け
    path('account/', include('allauth.urls')),
]

project/templates/layouts/_navbar.html
<div class="navbar">
    <div class="a_nav">
        <a href="{% url 'app2:graph' %}" class="nav_element">グラフの表示</a>
        <a href="{% url 'app2:index' %}" class="nav_element">コンディションの詳細</a>
        <a href="{% url 'app2:create_condition' %}" class="nav_element">コンディションの入力</a>
        <a href="{% url 'app3:nutrition' %}" class="nav_element">食事の詳細</a>
        <a href="{% url 'app3:create_nutrition' %}" class="nav_element">食事詳細入力</a>
        <a href="{% url 'app3:create_target' %}" class="nav_element">目標摂取カロリー入力</a>
        <a href="/account/logout" class="nav_element"><font color="red">ログアウト</font></a>
    </div>
</div>

project/templates/layouts/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}title{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block contents %}
    コンテンツがありません
    {% endblock contents %}
</body>
</html>

project/templates/layouts/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}title{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include '../layouts/_navbar.html' %}
    <div class="main">
    {% block contents %}
    コンテンツがありません
    {% endblock contents %}
    </div>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

project/templates/layouts/base3.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}title{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include '../layouts/_navbar.html' %}
    <div class="main">
    {% block contents %}
    コンテンツがありません
    {% endblock contents %}
    </div>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>